### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by Siq-Andre** [BiellSouza2005/HangmanReact#8]
Create a template for main page in figma

**Comment by iangodinho** [comment]
https://www.figma.com/design/dSbSwrOhIpU2yd7vbUZRcW/Hangaman?node-id=0-1&t=wF8FpQWWbcaSyyox-1

**Comment by iangodinho** [comment]
https://www.figma.com/design/dSbSwrOhIpU2yd7vbUZRcW/Hangaman?node-id=0-1&t=wF8FpQWWbcaSyyox-1
